import localFont from 'next/font/local';
import { headers } from 'next/headers';

import { wagmiConfig } from '~/lib/viem';

import type { Metadata } from 'next';
import { cookieToInitialState } from 'wagmi';
import { Web3Provider } from '~/providers';
import '~/styles/globals.css';

import { GrainEffect } from '~/components/grain-effect';
import { Toaster } from '~/components/ui/sonner';

const beatriceRegular = localFont({
  src: '../../public/beatrice-regular.woff2',
  variable: '--font-beatrice-regular',
});

const elgocAlt = localFont({
  src: '../../public/elgocAlt-medium.woff2',
  variable: '--font-elgocAlt',
});

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get('cookie')
  );

  return (
    <html lang='en'>
      <body
        className={`overflow-hidden font-sans ${beatriceRegular.variable} ${elgocAlt.variable}`}
      >
        <Web3Provider initialState={initialState}>{children}</Web3Provider>
        <Toaster />
        <GrainEffect />
      </body>
    </html>
  );
};

export default RootLayout;
