import localFont from 'next/font/local';

import type { Metadata } from 'next';
import { Navbar } from '~/components';
import { QueryProvider, SmoothScroll } from '~/providers';
import '~/styles/globals.css';

import { GrainEffect } from '~/components/grain-effect';
import { Toaster } from '~/components/ui/sonner';

const beatriceRegular = localFont({
  src: '../../public/beatrice-regular.woff2',
  variable: '--font-beatrice-regular',
});

const beatriceMedium = localFont({
  src: '../../public/beatrice-medium.woff2',
  variable: '--font-beatrice-medium',
});

const elgocAlt = localFont({
  src: '../../public/elgocAlt-medium.woff2',
  variable: '--font-elgocAlt',
});

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body
        className={`!overflow-x-hidden font-sans ${beatriceRegular.variable} ${elgocAlt.variable} ${beatriceMedium.variable}`}
      >
        <QueryProvider>
          <SmoothScroll>
            <GrainEffect />
            <Navbar />
            {children}
          </SmoothScroll>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
};

export default RootLayout;
